"""Unit tests for file deployment in new worker connect flow.

These tests verify that:
1. Local files (prompt.md, settings.json) are created correctly
2. Remote file verification is called after copy
3. The deployment fails fast if files are missing on remote
"""

import pytest
import os
import tempfile
from unittest.mock import patch, MagicMock, call


class TestLocalFileDeployment:
    """Test that local files are created before remote copy."""

    def test_prompt_md_written_to_local_tmp(self):
        """prompt.md should be written to local tmp dir when worker_prompt exists."""
        from orchestrator.agents import get_worker_prompt
        
        # Get the actual prompt template
        prompt = get_worker_prompt("test-session-id")
        
        # Verify it returns something
        assert prompt is not None, "Worker prompt template should exist"
        assert len(prompt) > 100, "Worker prompt should have substantial content"

    def test_settings_json_generated(self):
        """settings.json should be generated by generate_worker_hooks."""
        from orchestrator.agents.deploy import generate_worker_hooks
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            generate_worker_hooks(tmp_dir, "test-session-id", "http://127.0.0.1:8093")
            
            settings_path = os.path.join(tmp_dir, "settings.json")
            assert os.path.exists(settings_path), "settings.json should be created"
            
            # Verify it's valid JSON
            import json
            with open(settings_path) as f:
                settings = json.load(f)
            
            assert "hooks" in settings, "settings.json should have hooks"

    def test_bin_scripts_deployed(self):
        """CLI scripts should be deployed to bin directory."""
        from orchestrator.agents.deploy import deploy_worker_scripts
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            bin_dir = deploy_worker_scripts(tmp_dir, "test-session-id", "http://127.0.0.1:8093")
            
            assert os.path.exists(bin_dir), "bin directory should be created"
            
            # Check at least one script exists
            scripts = os.listdir(bin_dir)
            assert len(scripts) > 0, "bin directory should have scripts"


class TestDirectSSHCopy:
    """Test the direct SSH copy function signature and structure."""

    def test_copy_dir_to_rdev_ssh_function_exists(self):
        """_copy_dir_to_rdev_ssh function should exist with correct signature."""
        from orchestrator.terminal.session import _copy_dir_to_rdev_ssh
        import inspect
        
        sig = inspect.signature(_copy_dir_to_rdev_ssh)
        params = list(sig.parameters.keys())
        
        assert "local_dir" in params, "Should have local_dir parameter"
        assert "host" in params, "Should have host parameter"
        assert "remote_dir" in params, "Should have remote_dir parameter"

    def test_copy_dir_to_rdev_ssh_uses_subprocess(self):
        """_copy_dir_to_rdev_ssh should use subprocess for SSH."""
        from orchestrator.terminal.session import _copy_dir_to_rdev_ssh
        import inspect
        
        source = inspect.getsource(_copy_dir_to_rdev_ssh)
        
        assert "subprocess" in source, "Should use subprocess"
        assert "ssh" in source.lower(), "Should use SSH"
        assert "tar" in source, "Should use tar for transfer"


class TestRemoteVerification:
    """Test that remote file verification logic works correctly."""

    def test_session_py_uses_direct_ssh_copy(self):
        """Verify that session.py uses direct SSH for file copy."""
        import inspect
        from orchestrator.terminal.session import setup_rdev_worker
        
        source = inspect.getsource(setup_rdev_worker)
        
        # Check that direct SSH copy is used
        assert "_copy_dir_to_rdev_ssh" in source, "setup_rdev_worker should use _copy_dir_to_rdev_ssh"
        assert "RuntimeError" in source, "Should raise RuntimeError on copy failure"

    def test_direct_ssh_copy_raises_on_failure(self):
        """Verify that RuntimeError is raised when SSH copy fails."""
        import inspect
        from orchestrator.terminal.session import setup_rdev_worker
        
        source = inspect.getsource(setup_rdev_worker)
        
        # Verify the error handling is present
        assert "Failed to copy files to remote via SSH" in source, "Should have error for SSH copy failure"


class TestReconnectFileDeployment:
    """Test that reconnect also ensures files exist."""

    def test_ensure_local_configs_exist_creates_settings(self):
        """_ensure_local_configs_exist should create settings.json."""
        from orchestrator.session.reconnect import _ensure_local_configs_exist
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            _ensure_local_configs_exist(tmp_dir, "test-session-id")
            
            settings_path = os.path.join(tmp_dir, "configs", "settings.json")
            assert os.path.exists(settings_path), "settings.json should be created"

    def test_ensure_local_configs_exist_creates_bin_scripts(self):
        """_ensure_local_configs_exist should create bin scripts."""
        from orchestrator.session.reconnect import _ensure_local_configs_exist
        
        with tempfile.TemporaryDirectory() as tmp_dir:
            _ensure_local_configs_exist(tmp_dir, "test-session-id")
            
            bin_dir = os.path.join(tmp_dir, "bin")
            assert os.path.exists(bin_dir), "bin directory should be created"
            assert len(os.listdir(bin_dir)) > 0, "bin directory should have scripts"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
